name: Check generated files

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check-generated:
    name: Check generated files
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Restore Go cache
        uses: capnspacehook/cache-go/restore@9fca1a5a6020fb66aa66c17d3049cc69fd3c80d9 # v2.0.2

      - name: Ensure 'go generate' is clean
        run: |
          # shellcheck disable=SC2046
          go generate $(go list ./...)
          echo
          echo

          if ! git diff --name-only --exit-code; then
            echo "The files above need updating. Please run 'go generate'."
            exit 1
          fi
      
      - name: Save Go cache
        if: always()
        uses: capnspacehook/cache-go/save@9fca1a5a6020fb66aa66c17d3049cc69fd3c80d9 # v2.0.2
