name: Lint Go

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check-mod-tidy:
    name: Check if go.mod is tidy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Restore Go cache
        uses: capnspacehook/cache-go/restore@4f3bc64b4556d727693579cee939b5f7b7a96ecc # v2.1.1

      - name: Ensure go.mod was tidied
        run: |
          GO_VERSION="$(go version | grep -Po '\d\.\d\d\.\d+')"
          go mod tidy -compat "${GO_VERSION}"
          STATUS=$(git status --porcelain go.mod go.sum)
          if [[ -n $STATUS ]]; then
            echo "Running 'go mod tidy' modified go.mod and/or go.sum"
            echo "Run 'go mod tidy -compat ${GO_VERSION}' to fix"
            echo
            echo "Diff:"
            git diff
            exit 1
          fi

      - name: Save Go cache
        if: always()
        uses: capnspacehook/cache-go/save@4f3bc64b4556d727693579cee939b5f7b7a96ecc # v2.1.1

  check-test-symbols:
    name: Check for test symbols in main packages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Checkout tools go.mod
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: capnspacehook/go-workflows
          path: go-workflows
          sparse-checkout: |
            go.mod
            go.sum
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Restore Go cache
        uses: capnspacehook/cache-go/restore@4f3bc64b4556d727693579cee939b5f7b7a96ecc # v2.1.1

      - name: Check for test symbols
        run: |
          MAIN_PKGS="$(go list -f '{{if eq .Name "main"}}{{.ImportPath}}{{end}}' ./...)"
          #shellcheck disable=SC2086
          for main_pkg in ${MAIN_PKGS}; do
            for import in "testing" "pgregory.net/rapid" "github.com/stretchr/testify" "github.com/google/go-cmp" "github.com/matryer/is" "go.uber.org/goleak"; do
              # add the module to go.mod if it's not a stdlib package
              if echo "${import}" | grep -q '/'; then
                go get "${import}@latest"
              fi
              COUNT="$(go tool -modfile=go-workflows/go.mod goda tree reach\(${main_pkg}:all, ${import}/...\) | tee /dev/stderr | tr -d ' ' | wc -l)"
              if [ "${COUNT}" -gt 0 ]; then
                echo
                echo "Found test symbols in ${main_pkg} imported from ${import}"
                exit 1
              fi
            done
          done

      - name: Save Go cache
        if: always()
        uses: capnspacehook/cache-go/save@4f3bc64b4556d727693579cee939b5f7b7a96ecc # v2.1.1

  go-fix:
    name: Run go fix
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Restore Go cache
        uses: capnspacehook/cache-go/restore@4f3bc64b4556d727693579cee939b5f7b7a96ecc # v2.1.1

      - name: Run go fix
        run: |
          go fix -diff ./...

      - name: Save Go cache
        if: always()
        uses: capnspacehook/cache-go/save@4f3bc64b4556d727693579cee939b5f7b7a96ecc # v2.1.1

  staticcheck:
    name: Run Staticcheck
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Restore Go cache
        uses: capnspacehook/cache-go/restore@4f3bc64b4556d727693579cee939b5f7b7a96ecc # v2.1.1

      - name: Lint with staticcheck
        uses: dominikh/staticcheck-action@9716614d4101e79b4340dd97b10e54d68234e431 # v1.4.1
        with:
          install-go: false

      - name: Save Go cache
        if: always()
        uses: capnspacehook/cache-go/save@4f3bc64b4556d727693579cee939b5f7b7a96ecc # v2.1.1

  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
