name: Lint workflows

on:
  workflow_call:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/*"
  pull_request:
    branches:
      - "*"
    paths:
      - ".github/workflows/*"

  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  run-actionlint:
    name: Run actionlint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Checkout tools go.mod
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: capnspacehook/go-workflows
          path: go-workflows
          sparse-checkout: |
            go.mod
            go.sum
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Restore Go cache
        uses: capnspacehook/cache-go/restore@4f3bc64b4556d727693579cee939b5f7b7a96ecc # v2.1.1

      - name: Run actionlint
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          go tool -modfile=go-workflows/go.mod actionlint

      - name: Save Go cache
        if: always()
        uses: capnspacehook/cache-go/save@4f3bc64b4556d727693579cee939b5f7b7a96ecc # v2.1.1

  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif (used by zizmor-action) to upload SARIF files.
      contents: read         # Only needed for private repos. Needed to clone the repo.
      actions: read          # Only needed for private repos. Needed for upload-sarif to read workflow run info.
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02 # v0.6.0
