name: Release

on:
  workflow_call:
    inputs:
      release-binaries:
        description: If binaries should be released or not
        default: true
        required: false
        type: boolean
      release-image:
        description: If a Docker image should be released or not
        default: true
        required: false
        type: boolean
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  release-binaries:
    name: Release binaries
    runs-on: ubuntu-latest
    if: inputs.release-binaries == 'true' && github.ref_type == 'tag'
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout tags
        run: git fetch --force --tags

      - name: Install Go
        uses: WillAbides/setup-go-faster@v1.11.0
        with:
          go-version-file: go.mod

      - name: Cache Go files
        uses: capnspacehook/cache-go@v1

      - name: Install cosign
        uses: sigstore/cosign-installer@main

      - name: Build and release with goreleaser
        uses: goreleaser/goreleaser-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: goreleaser
          version: latest
          args: release

  release-image:
    name: Release image
    runs-on: ubuntu-latest
    if: inputs.release-image == 'true'
    timeout-minutes: 15
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cosign
        uses: sigstore/cosign-installer@main

      - name: Install Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build list of Docker tags to use
        id: tag-types
        run: |
          if [[ ${{ contains(github.ref, 'tag') }} == true ]]; then
            TAGS="
            type=semver,pattern={{major}},priority=920
            type=semver,pattern={{major}}.{{minor}},priority=910
            type=semver,pattern={{version}},priority=900
            type=ref,event=branch
            type=sha,format=long"
          else
            TAGS="
            type=ref,event=branch
            type=sha,format=long"
          fi

          # https://trstringer.com/github-actions-multiline-strings
          {
            echo "TAGS<<EOF"
            echo "$TAGS"
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Set Docker labels and tags
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
          tags: ${{ env.TAGS }}

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest git tag
        id: get-tag
        uses: olegtarasov/get-tag@v2.1

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ steps.get-tag.outputs.tag }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Sign container image
        run: cosign sign --yes ghcr.io/${{ github.repository }}@${{ steps.build-push.outputs.digest }}
