name: Reproduce binary

on:
  workflow_call:
    inputs:
      extra-build-flags:
        description: Build flags that aren't detected by gorepro
        required: false
        type: string

jobs:
  repro-binary:
    name: Check if binary is reproducible
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Restore Go cache
        uses: capnspacehook/cache-go/restore@9fca1a5a6020fb66aa66c17d3049cc69fd3c80d9 # v2.0.2

      - name: Build with goreleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser
          version: latest
          args: build --verbose --single-target --snapshot -o out

      - name: Attempt to reproduce binary
        run: |
          go install github.com/capnspacehook/gorepro@master
          if ! gorepro -b="${INPUTS_EXTRA_BUILD_FLAGS}" -v out; then
            go version -m out
            go version -m out.repro
            exit 1
          fi
        env:
          INPUTS_EXTRA_BUILD_FLAGS: ${{ inputs.extra-build-flags }}

      - name: Save Go cache
        if: always()
        uses: capnspacehook/cache-go/save@9fca1a5a6020fb66aa66c17d3049cc69fd3c80d9 # v2.0.2
