name: Vulnerability scan

on:
  workflow_call:

permissions:
  contents: read

jobs:
  govulncheck:
    name: Run govulncheck
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Checkout tools go.mod
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: capnspacehook/go-workflows
          path: go-workflows
          sparse-checkout: |
            go.mod
            go.sum
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Restore Go cache
        uses: capnspacehook/cache-go/restore@1c52528ce96ee3f9214894a877c4db64bb206558 # v2.1.0

      - name: Scan code for vulnerabilities
        run: |
          go tool -modfile=go-workflows/go.mod govulncheck ./...

      - name: Save Go cache
        if: always()
        uses: capnspacehook/cache-go/save@1c52528ce96ee3f9214894a877c4db64bb206558 # v2.1.0
