name: Vulnerability scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "00 13 * * 1"

  workflow_dispatch: {}

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: golang/govulncheck-action@v1.0.1
        with:
          go-version-file: go.mod
